builds:
  -
    binary: rancher-deploy
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    hooks:
      pre: vgo vendor

archive:
  format: tar.gz
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip

sign:
   artifacts: checksum
